services:
  nginx:
    image: nginx:latest
    container_name: 'nginx-container'
    environment:
      TZ: Asia/Tokyo
    ports:
      - 443:443
      - 80:80
    volumes:
      #nginxの設定ファイル
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      #nginxのログファイル
      - ./nginx/log/:/var/log/nginx/
      - ./nginx/html/:/usr/share/nginx/html/
      - ./nginx/ssl/:/usr/share/nginx/ssl/